name = "warden-worker"
main = "build/index.js"
compatibility_date = "2025-09-19"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "vault1"
database_name = "vault1"
database_id = "eb2b32e7-3ffa-46c6-8a65-a39997623d0e"
